DELETE http://localhost:3001/api/users/6755ed2986e92a6d11e71044

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@j.com",
  "password": "password123"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "j@j.com",
  "password": "password1235"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "",
  "email": "j@j.com",
  "password": "password1235"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "fasdfa",
  "email": "j@jfadsfsd.com",
  "password": "password1235"
}

###
GET http://localhost:3001/api/users