GET http://localhost:8080/api/events 

###
GET http://localhost:8080/api/events/---------------------

###
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Test Event: Super Cool NZPMC Event",
  "description": "Event 1 description imagine",
  "date": "2021-12-12"
}

###
PUT http://localhost:8080/api/events/---------------------
Content-Type: application/json

{
  "description": "Event 1 description modified more"
}

###
DELETE http://localhost:8080/api/events/---------------------